--[[
    GlassLib Build Script
    Compiles all modules into a single loadstring-compatible file
    
    Usage:
        luau build.lua
        -- or
        lua build.lua
    
    Outputs GlassLib_Compiled.lua
--]]

local concat = table.concat
local insert = table.insert
local format = string.format
local readfile = io.open

-- ══════════════════════════════════════════════════════════════
-- FILE LISTING (order matters for dependency resolution)
-- ══════════════════════════════════════════════════════════════

local MODULE_ORDER = {
	"src/util.lua",
	"src/theme.lua",
	"src/acrylic.lua",
	"src/config.lua",
	"src/notify.lua",
	"src/dialog.lua",
	"src/toggle.lua",
	"src/elements/init.lua",
	"src/elements/button.lua",
	"src/elements/toggle.lua",
	"src/elements/slider.lua",
	"src/elements/dropdown.lua",
	"src/elements/textinput.lua",
	"src/elements/keybind.lua",
	"src/elements/colorpicker.lua",
	"src/elements/label.lua",
	"src/elements/paragraph.lua",
	"src/elements/divider.lua",
	"src/section.lua",
	"src/tab.lua",
	"src/window.lua",
	"init.lua",
}

-- ══════════════════════════════════════════════════════════════
-- MODULE NAME RESOLUTION
-- Maps file paths to module names used in require()
-- ══════════════════════════════════════════════════════════════

local function pathToModuleName(path)
	-- src/util.lua -> "util"
	-- src/elements/button.lua -> "button"
	local name = path:match("src/(.-)%.lua$")
	if not name then
		name = path:match("(.-)%.lua$")
	end
	-- Remove init
	if name == "elements/init" then
		return "elements"
	end
	-- Get just the filename
	name = name:match("([^/]+)$") or name
	return name
end

local function resolveRequire(originalRequire, moduleName)
	-- Replace require(script.Parent.xxx) with module lookup
	-- We'll use a simple module table approach
	return format('_MODULES["%s"]', moduleName)
end

-- ══════════════════════════════════════════════════════════════
-- READ AND COMPILE
-- ══════════════════════════════════════════════════════════════

local output = {}

-- Header
insert(output, "--[[")
insert(output, "    GlassLib v2.0.0 (Compiled)")
insert(output, "    Liquid Glass UI Library for Roblox Exploits")
insert(output, "")
insert(output, "    Generated by build.lua — do not edit manually")
insert(output, "--]]")
insert(output, "")
insert(output, "local _MODULES = {}")
insert(output, "local _LOADED = {}")
insert(output, "")
insert(output, "local function require(moduleName)")
insert(output, "    if _LOADED[moduleName] then")
insert(output, "        return _LOADED[moduleName]")
insert(output, "    end")
insert(output, "    local mod = _MODULES[moduleName]")
insert(output, "    if not mod then")
insert(output, '        error("GlassLib: module not found: " .. moduleName, 2)')
insert(output, "    end")
insert(output, "    _LOADED[moduleName] = true")
insert(output, "    local result = mod()")
insert(output, "    _LOADED[moduleName] = result")
insert(output, "    return result")
insert(output, "end")
insert(output, "")

-- Process each module
local moduleMap = {}

for _, filePath in ipairs(MODULE_ORDER) do
	local f = io.open(filePath, "r")
	if f then
		local content = f:read("*a")
		f:close()
		
		local moduleName = pathToModuleName(filePath)
		moduleMap[moduleName] = true
		
		-- Clean up the content
		-- Remove script.Parent references and replace with module lookups
		content = content:gsub('require%(script%.Parent%.Parent%.(%w+)%)', function(name)
			return format('_MODULES["%s"]', name)
		end)
		content = content:gsub('require%(script%.Parent%.(%w+)%)', function(name)
			return format('_MODULES["%s"]', name)
		end)
		content = content:gsub('require%(script%.(%w+)%)', function(name)
			return format('_MODULES["%s"]', name)
		end)
		
		-- Wrap in module function
		insert(output, format('-- Module: %s', filePath))
		insert(output, format('_MODULES["%s"] = function()', moduleName))
		insert(output, content)
		insert(output, "end")
		insert(output, "")
		
		print(format("  Packed: %s -> %s", filePath, moduleName))
	else
		print(format("  WARNING: File not found: %s", filePath))
	end
end

-- Main entry: call the init module
insert(output, "")
insert(output, "-- ══════════════════════════════════════════════════════════════")
insert(output, "-- ENTRY POINT")
insert(output, "-- ══════════════════════════════════════════════════════════════")
insert(output, 'return require("init")')

-- Write output
local outputFile = io.open("GlassLib_Compiled.lua", "w")
if outputFile then
	outputFile:write(concat(output, "\n"))
	outputFile:close()
	print("\nBuild complete! Output: GlassLib_Compiled.lua")
	print("Total modules: " .. #MODULE_ORDER)
else
	print("ERROR: Could not write output file")
end
